{{- if .Values.redisCommander.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redisCommander.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "hotel-reservation.serviceLabels" (dict "serviceName" .Values.redisCommander.name "context" .) | nindent 4 }}
    component: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hotel-reservation.serviceSelectorLabels" (dict "serviceName" .Values.redisCommander.name "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hotel-reservation.serviceSelectorLabels" (dict "serviceName" .Values.redisCommander.name "context" .) | nindent 8 }}
        component: infrastructure
    spec:
      containers:
      - name: {{ .Values.redisCommander.name }}
        image: {{ .Values.redisCommander.image.repository }}:{{ .Values.redisCommander.image.tag }}
        imagePullPolicy: {{ .Values.redisCommander.image.pullPolicy | default .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.redisCommander.service.targetPort }}
          name: http
        env:
        - name: REDIS_HOSTS
          value: "minikube:{{ .Values.redis.name }}:{{ .Values.redis.service.port }}"
        {{- include "hotel-reservation.resources" .Values.redisCommander.resources | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisCommander.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "hotel-reservation.serviceLabels" (dict "serviceName" .Values.redisCommander.name "context" .) | nindent 4 }}
    component: infrastructure
spec:
  type: {{ .Values.redisCommander.service.type }}
  ports:
  - port: {{ .Values.redisCommander.service.port }}
    targetPort: {{ .Values.redisCommander.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "hotel-reservation.serviceSelectorLabels" (dict "serviceName" .Values.redisCommander.name "context" .) | nindent 4 }}
{{- end }}

